import modal

app = modal.App("chat-animica-modal")
image = modal.Image.debian_slim(python_version="3.11").pip_install("fastapi[standard]", "pydantic")


@app.function(image=image)
@modal.asgi_app()
def fastapi_app():
    from fastapi import FastAPI
    from pydantic import BaseModel

    web = FastAPI()

    class ChatIn(BaseModel):
      prompt: str
      context: dict | None = None

    @web.post("/chat")
    async def chat(payload: ChatIn):
      return {
        "content": f"// Generated by Modal\ncontract Generated {{ fn prompt() -> string {{ return '{payload.prompt[:40]}' }} }}",
        "abi": [{"name": "prompt", "type": "function"}],
        "manifest": {"runtime": "animica-v1"}
      }

    return web
