packages:
  - sdk
  - studio-wasm
  - website
  - explorer-web
  - studio-web
  - apps/wallet-extension
  - wallet
  - apps/miner-dashboard
  - apps/animica-tokens
  - apps/dapp-ide
  - apps/banm-bridge-web
  - apps/banm-bridge-admin
  - evm/banm-bridge
  - explorer2
  - explorer2/*
  - services/exchange-api
  - apps/admin-web
  - apps/dapp-ide
