packages:
  - sdk
  - packages/shared/*
  - packages/sdk/*
  - studio-wasm
  - website
  - explorer-web
  - studio-web
  - apps/aicf-web
  - apps/aicf-provider
  - apps/aicf-api
  - apps/aicf-docs
  - apps/wallet-extension
  - wallet
  - apps/miner-dashboard
  - apps/animica-tokens
  - apps/dapp-ide
  - apps/banm-bridge-web
  - apps/banm-bridge-admin
  - evm/banm-bridge
  - explorer2
  - explorer2/*
  - services/exchange-api
  - services/scheduler
  - services/job-worker
  - services/usage-meter
  - services/provider-control-plane
  - services/dispute-worker
  - services/treasury-worker
  - services/contract-job-watcher
  - services/fulfillment-scheduler
  - services/result-submitter
  - services/finalization-worker
  - services/usdan-api
  - apps/admin-web
  - apps/dapp-ide
  - apps/usdan-web
  - provider-daemon
