"""
Test chain reset validation and genesis hash verification.

This test ensures that:
1. The new genesis hash matches the expected constant from consensus/build_genesis.py
2. Nodes refuse to start with old chain data (wrong genesis)
3. Fresh nodes start at height 0 with the new genesis

NOTE: The canonical genesis hash is generated by consensus/build_genesis.py using
core/genesis/genesis.json as the source of truth for header inputs.
"""

import json
from pathlib import Path
import tempfile

import pytest

from consensus import params as consensus_params
from core.genesis.loader import compute_genesis_hash
from core.db.sqlite import SQLiteKV
from core.db.block_db import BlockDB
from p2p.errors import P2PError


# These are test-only files we'll check
GENESIS_PATH = Path(__file__).resolve().parent / "core" / "genesis" / "mainnet.json"
OLD_GENESIS_HASH = "0x5868b982d22fe2eb4eb15567dd6afdbae453001388bc23a2517639729428cfda"
NEW_GENESIS_HASH = "0x6a27e93193020cd00fe429ef0ffac1c3a774268a589c2911ac396dd3cba2d242"


def test_new_genesis_hash_is_correct():
    """
    Verify that the new genesis hash matches the expected constant after reset.
    
    This test ensures that consensus.params.GENESIS_HASH_HEX has been updated
    to the new genesis hash generated from the updated timestamp and message.
    """
    # The genesis hash should match the new reset hash
    assert consensus_params.GENESIS_HASH_HEX == NEW_GENESIS_HASH, (
        f"Genesis hash mismatch!\n"
        f"Expected: {NEW_GENESIS_HASH}\n"
        f"Got: {consensus_params.GENESIS_HASH_HEX}\n"
        f"Run: python consensus/build_genesis.py --verify"
    )
    
    # Also verify the bytes version matches
    expected_bytes = bytes.fromhex(NEW_GENESIS_HASH[2:])
    assert consensus_params.GENESIS_HASH == expected_bytes


def test_genesis_timestamp_updated():
    """Verify that genesis timestamp was updated for the reset."""
    # The timestamp should be 2026-01-18, not the old 2026-01-16
    assert consensus_params.GENESIS_TIMESTAMP_UTC == "2026-01-18T00:00:00Z", (
        f"Genesis timestamp not updated!\n"
        f"Expected: 2026-01-18T00:00:00Z\n"
        f"Got: {consensus_params.GENESIS_TIMESTAMP_UTC}"
    )


def test_genesis_message_updated():
    """Verify that genesis message was updated for the reset."""
    # The message should mention "Jan 2026" reset
    assert "Jan 2026" in consensus_params.GENESIS_MESSAGE, (
        f"Genesis message not updated!\n"
        f"Got: {consensus_params.GENESIS_MESSAGE}"
    )


def test_genesis_file_hash_matches_pinned():
    """
    Verify that core/genesis/mainnet.json matches the pinned consensus hash.
    """
    computed_hash = compute_genesis_hash(GENESIS_PATH)

    assert computed_hash == NEW_GENESIS_HASH, (
        f"Genesis file produced unexpected hash!\n"
        f"Expected: {NEW_GENESIS_HASH}\n"
        f"Got: {computed_hash}\n"
        "Check core/genesis/mainnet.json and core/network_params pinning."
    )


def test_old_db_with_wrong_genesis_is_rejected():
    """
    Verify that attempting to use a database initialized with an old
    genesis (wrong genesis hash) is rejected by checking the genesis guard.
    
    This test validates the genesis guard mechanism without importing heavy
    RPC dependencies.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        db_path = Path(tmpdir) / "old.db"
        
        # Create a DB and manually set an old genesis hash
        kv = SQLiteKV(str(db_path))
        block_db = BlockDB(kv)
        
        # Simulate old genesis hash in the DB
        old_hash_bytes = bytes.fromhex(OLD_GENESIS_HASH[2:])
        block_db.set_genesis_hash(old_hash_bytes)
        block_db.set_head(0, old_hash_bytes)
        block_db.set_canonical(0, old_hash_bytes)
        
        # Close DB to flush writes
        kv.close()
        
        # Now check that reading the genesis hash shows it's different
        kv2 = SQLiteKV(str(db_path))
        block_db2 = BlockDB(kv2)
        stored_genesis = block_db2.get_genesis_hash()
        kv2.close()
        
        assert stored_genesis == old_hash_bytes, "Old hash should be in DB"
        assert stored_genesis != bytes.fromhex(NEW_GENESIS_HASH[2:]), (
            "DB should have different genesis than current"
        )


def test_mainnet_json_timestamp_updated():
    """
    Verify that core/genesis/mainnet.json was updated with new timestamp
    for the reset.
    """
    if not GENESIS_PATH.exists():
        pytest.skip(f"Genesis file not found: {GENESIS_PATH}")
    
    with open(GENESIS_PATH, 'r') as f:
        genesis = json.load(f)
    
    # Check timestamp matches
    assert genesis["genesisTime"] == "2026-01-18T00:00:00Z", (
        f"mainnet.json timestamp not updated!\n"
        f"Expected: 2026-01-18T00:00:00Z\n"
        f"Got: {genesis['genesisTime']}"
    )
    
    # Check meta version references reset
    assert "reset" in genesis["meta"]["genesis_version"].lower(), (
        f"mainnet.json meta should mention reset"
    )


def test_old_genesis_hash_is_documented():
    """
    Verify that the old genesis hash is documented in consensus/params.py
    for reference and troubleshooting.
    """
    # Read the params.py file
    params_path = Path(__file__).resolve().parent / "consensus" / "params.py"
    params_content = params_path.read_text()
    
    # The old hash should be mentioned in a comment
    assert OLD_GENESIS_HASH in params_content, (
        f"Old genesis hash {OLD_GENESIS_HASH} should be documented in consensus/params.py "
        "for troubleshooting and reference"
    )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
