#!/usr/bin/env bash
# Manual verification script for genesis peer eligibility fix
# 
# This script provides steps to manually verify that the genesis sync fix works.
# It should be run after deploying the fix to a test environment.

set -e

echo "========================================================================"
echo "Genesis Peer Eligibility Fix - Manual Verification Guide"
echo "========================================================================"
echo ""
echo "This fix addresses the issue where nodes stuck at genesis (height 0)"
echo "could not sync because they rejected each other as 'no_chain_data'."
echo ""
echo "Prerequisites:"
echo "  - Two nodes deployed with the fix"
echo "  - Both nodes at genesis (height 0)"
echo "  - Nodes connected to each other"
echo ""
echo "========================================================================"
echo "Step 1: Check Initial State"
echo "========================================================================"
echo ""
echo "On Node 1, run:"
echo "  animica node status"
echo ""
echo "Expected output:"
echo "  - Head height: 0"
echo "  - Sync status: IDLE or SYNCING"
echo "  - Peers: 1+ connected"
echo ""
echo "On Node 2, run:"
echo "  animica node status"
echo ""
echo "Expected output:"
echo "  - Head height: 0"
echo "  - Sync status: IDLE or SYNCING"
echo "  - Peers: 1+ connected"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Step 2: Check Peer Eligibility"
echo "========================================================================"
echo ""
echo "On Node 1, run:"
echo "  animica debug sync-dump"
echo ""
echo "Expected output:"
echo "  - Best peer head: Should show peer at height 0 or higher"
echo "  - Should NOT show 'no_chain_data' errors"
echo "  - Peers should be listed as eligible for sync"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Step 3: Trigger Block Production"
echo "========================================================================"
echo ""
echo "On Node 2, mine a block:"
echo "  animica mining start --address <your-address>"
echo "  # Wait for block to be mined (may take a few seconds to minutes)"
echo "  animica mining stop"
echo ""
echo "Or manually create a block using the RPC:"
echo "  animica rpc call mining.mine '{\"params\": [\"<your-address>\"]}'"
echo ""
echo "Verify block was created:"
echo "  animica node status"
echo ""
echo "Expected output on Node 2:"
echo "  - Head height: 1"
echo "  - Chain should show block 1"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Step 4: Verify Sync Progresses on Node 1"
echo "========================================================================"
echo ""
echo "On Node 1, wait a few seconds then run:"
echo "  animica node status"
echo ""
echo "Expected output:"
echo "  - Head height: 1 (synced from Node 2)"
echo "  - Sync status: SYNCED or IDLE"
echo "  - Should show recent block with height 1"
echo ""
echo "If sync doesn't progress automatically, force it:"
echo "  animica sync force"
echo "  # Wait a few seconds"
echo "  animica node status"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Step 5: Verify Continuous Sync"
echo "========================================================================"
echo ""
echo "On Node 2, mine another block:"
echo "  animica mining start --address <your-address>"
echo "  # Wait for block to be mined"
echo "  animica mining stop"
echo ""
echo "On Node 1, verify it syncs the new block:"
echo "  animica node status"
echo ""
echo "Expected output:"
echo "  - Head height: 2 (synced from Node 2)"
echo "  - Should show both blocks"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Step 6: Check for Regressions"
echo "========================================================================"
echo ""
echo "Verify normal sync behavior still works:"
echo ""
echo "1. Check that peers at higher heights are preferred:"
echo "   animica peer list"
echo "   # Peers with higher heights should be used for sync"
echo ""
echo "2. Check that sync continues working past genesis:"
echo "   animica sync status"
echo "   # Should show normal sync status, not stuck"
echo ""
echo "3. Check logs for any errors:"
echo "   docker logs animica-mainnet-node | tail -50"
echo "   # Should not show 'no_chain_data' errors when peers are available"
echo ""
echo "Press Enter to continue..."
read

echo "========================================================================"
echo "Verification Complete!"
echo "========================================================================"
echo ""
echo "Summary of expected behavior:"
echo ""
echo "✓ Nodes at genesis (height 0) should see each other as eligible peers"
echo "✓ When one node mines/receives a block, the other should sync it"
echo "✓ Sync should progress normally from genesis through all heights"
echo "✓ No 'no_chain_data' errors when peers with height 0 are connected"
echo "✓ No regression in normal sync behavior at higher heights"
echo ""
echo "If all tests pass, the fix is working correctly!"
echo ""
echo "Note: If sync doesn't progress, check:"
echo "  - Network connectivity between nodes"
echo "  - Genesis hash matches between nodes"
echo "  - Chain ID matches between nodes"
echo "  - Firewall/port configuration"
echo ""
