from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

from core.genesis.loader import (
    compute_state_root_from_alloc,
    load_and_init_genesis,
)
from core.genesis.genesis_loader import GenesisNotFoundError
from core.utils.serialization import to_canonical_json


def _hex(b: bytes) -> str:
    return "0x" + b.hex()


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _header_to_dict(header: Any) -> dict[str, Any]:
    raw = asdict(header)
    out: dict[str, Any] = {}
    for key, value in raw.items():
        if isinstance(value, (bytes, bytearray)):
            out[key] = _hex(bytes(value))
        else:
            out[key] = value
    out["hash"] = _hex(bytes(header.hash()))
    return out


def _build_genesis(
    *,
    chain_id: int,
    genesis_time: str,
    allocations: list[dict[str, Any]],
    consensus: dict[str, Any],
    network: str,
    description: str,
    params_ref_path: str,
    params_ref_hash: str,
    fork_id: int | None,
) -> dict[str, Any]:
    genesis = {
        "meta": {"version": 1, "description": description},
        "chainId": int(chain_id),
        "network": network,
        "genesisTime": genesis_time,
        "unit": {"symbol": "ANM", "decimals": 9},
        "paramsRef": {"path": params_ref_path, "sha3_256": params_ref_hash},
        "algPolicyRoot": "0x" + ("00" * 64),
        "beacon": {"seed": "0x" + ("11" * 32), "round": 0},
        "economics": {"premineTotal": "0", "premineBreakdownANM": {}},
        "alloc": allocations,
        "consensus": consensus,
        "notes": [
            "Generated by tools/genesis/create_genesis.py",
            "All balances are integers in base units (10^9 = 1 ANM).",
        ],
    }
    if fork_id is not None:
        genesis["forkId"] = int(fork_id)
    return genesis


def main() -> None:
    ap = argparse.ArgumentParser(description="Deterministically build Animica genesis files")
    ap.add_argument("--chain-id", type=int, required=True)
    ap.add_argument("--genesis-time", required=True, help="RFC3339 timestamp for genesis")
    ap.add_argument("--network", default="animica-mainnet")
    ap.add_argument("--description", default="Animica genesis (deterministic)")
    ap.add_argument("--alloc-file", type=Path, help="JSON list of allocations")
    ap.add_argument("--consensus-file", type=Path, help="JSON mapping of consensus params")
    ap.add_argument("--params-ref-path", default="spec/params.yaml")
    ap.add_argument("--params-ref-hash", default="0x" + ("00" * 32))
    ap.add_argument("--fork-id", help="Explicit fork id (int or hex)")
    ap.add_argument("--output-dir", type=Path, default=Path("."))
    ap.add_argument("--db-uri", help="Optional DB URI to bootstrap with this genesis")
    args = ap.parse_args()

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    allocations = []
    if args.alloc_file:
        allocations = _load_json(args.alloc_file)
        if not isinstance(allocations, list):
            raise ValueError("alloc-file must contain a JSON list")

    consensus = {"initialThetaMicro": 1_000_000, "gammaCapMicro": 2_000_000}
    if args.consensus_file:
        consensus = _load_json(args.consensus_file)
        if not isinstance(consensus, dict):
            raise ValueError("consensus-file must contain a JSON object")

    fork_id = None
    if args.fork_id is not None:
        v = str(args.fork_id).strip().lower()
        fork_id = int(v, 16) if v.startswith("0x") else int(v)

    genesis = _build_genesis(
        chain_id=args.chain_id,
        genesis_time=args.genesis_time,
        allocations=allocations,
        consensus=consensus,
        network=args.network,
        description=args.description,
        params_ref_path=args.params_ref_path,
        params_ref_hash=args.params_ref_hash,
        fork_id=fork_id,
    )

    state_root = compute_state_root_from_alloc(genesis["alloc"])
    genesis["stateRoot"] = _hex(state_root)

    from core.genesis import loader as genesis_loader

    header = genesis_loader._build_genesis_header(genesis, state_root)  # type: ignore[attr-defined]
    genesis["genesisHeader"] = _header_to_dict(header)

    genesis_path = output_dir / "genesis.json"
    genesis_path.write_text(to_canonical_json(genesis), encoding="utf-8")

    hash_path = output_dir / "genesis.hash"
    hash_path.write_text(_hex(bytes(header.hash())) + "\n", encoding="utf-8")

    if args.db_uri:
        try:
            load_and_init_genesis(str(genesis_path), args.db_uri, log=True)
        except GenesisNotFoundError as exc:
            raise RuntimeError(f"Failed to bootstrap DB: {exc}") from exc


if __name__ == "__main__":
    main()
