from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any, Iterable

from core.genesis.loader import compute_state_root_from_alloc
from core.utils.hash import sha3_256
from core.utils.serialization import to_canonical_json


def _hex(b: bytes) -> str:
    return "0x" + b.hex()


def _load_alloc(path: Path) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("alloc file must be a JSON list of allocations")
    return data


def _seed_to_hex(seed_message: str) -> str:
    return _hex(sha3_256(seed_message.encode("utf-8")))


def _header_to_dict(header: Any) -> dict[str, Any]:
    raw = asdict(header)
    out: dict[str, Any] = {}
    for key, value in raw.items():
        if isinstance(value, (bytes, bytearray)):
            out[key] = _hex(bytes(value))
        else:
            out[key] = value
    out["hash"] = _hex(bytes(header.hash()))
    return out


def build_genesis(
    *,
    chain_id: int,
    genesis_time: str,
    seed_message: str,
    theta_micro: int,
    gamma_cap_micro: int,
    allocations: Iterable[dict[str, Any]],
    network: str,
    description: str,
    params_ref_path: str,
    params_ref_hash: str,
    genesis_version: str,
) -> dict[str, Any]:
    genesis = {
        "meta": {
            "version": 2,
            "genesis_version": genesis_version,
            "description": description,
            "seed_message": seed_message,
        },
        "chainId": int(chain_id),
        "network": network,
        "genesisTime": genesis_time,
        "unit": {"symbol": "ANM", "decimals": 9},
        "paramsRef": {"path": params_ref_path, "sha3_256": params_ref_hash},
        "algPolicyRoot": "0x" + ("00" * 64),
        "beacon": {"seed": _seed_to_hex(seed_message), "round": 0},
        "economics": {"premineTotal": "0", "premineBreakdownANM": {}},
        "alloc": list(allocations),
        "consensus": {
            "initialThetaMicro": int(theta_micro),
            "gammaCapMicro": int(gamma_cap_micro),
        },
        "notes": [
            "Generated by tools/genesis/make_genesis.py",
            "All balances are integers in base units (10^9 = 1 ANM).",
        ],
    }
    return genesis


def main() -> None:
    ap = argparse.ArgumentParser(description="Deterministically build Animica genesis files")
    ap.add_argument("--seed-message", required=True, help="Seed message used to derive beacon seed")
    ap.add_argument("--genesis-time", required=True, help="RFC3339 timestamp for genesis")
    ap.add_argument("--chain-id", type=int, default=1)
    ap.add_argument("--theta-micro", type=int, default=1_000_000)
    ap.add_argument("--gamma-cap-micro", type=int, default=2_000_000)
    ap.add_argument("--network", default="animica-mainnet")
    ap.add_argument("--description", default="Animica genesis (deterministic)")
    ap.add_argument("--params-ref-path", default="spec/params.yaml")
    ap.add_argument("--params-ref-hash", default="0x" + ("00" * 32))
    ap.add_argument("--genesis-version", default="reset-2026-05")
    ap.add_argument("--alloc-file", type=Path, help="JSON list of allocations")
    ap.add_argument("--output-genesis", type=Path, help="Write genesis JSON to this path")
    args = ap.parse_args()

    allocations: list[dict[str, Any]] = []
    if args.alloc_file:
        allocations = _load_alloc(args.alloc_file)

    genesis = build_genesis(
        chain_id=args.chain_id,
        genesis_time=args.genesis_time,
        seed_message=args.seed_message,
        theta_micro=args.theta_micro,
        gamma_cap_micro=args.gamma_cap_micro,
        allocations=allocations,
        network=args.network,
        description=args.description,
        params_ref_path=args.params_ref_path,
        params_ref_hash=args.params_ref_hash,
        genesis_version=args.genesis_version,
    )

    from core.genesis import loader as genesis_loader

    state_root = compute_state_root_from_alloc(genesis["alloc"])
    header = genesis_loader._build_genesis_header(genesis, state_root)  # type: ignore[attr-defined]
    header_dict = _header_to_dict(header)

    print("Genesis hash:", header_dict["hash"])
    print("State root:", _hex(state_root))
    print("Beacon seed:", genesis["beacon"]["seed"])
    print("Header fields:")
    print(json.dumps(header_dict, indent=2, sort_keys=True))

    if args.output_genesis:
        output_path = args.output_genesis.expanduser().resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        genesis["stateRoot"] = _hex(state_root)
        genesis["genesisHeader"] = header_dict
        output_path.write_bytes(to_canonical_json(genesis))


if __name__ == "__main__":
    main()
