# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json
# Version (root) manifest for Animica Internet 0.1.0
PackageIdentifier: Animica.AnimicaInternet
PackageVersion: 0.1.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
