//! Animica SDK (Rust)
//!
//! Typed clients, wallet helpers, transactions, contracts, DA/AICF/Randomness services,
//! and light verification for the Animica network.
//!
//! ### Features
//! - `native` (default): reqwest + tokio-tungstenite networking
//! - `wasm`: gloo-net + wasm-bindgen networking
//! - `pq`: post-quantum signers via liboqs (optional)
//!
//! See `sdk/rust/README.md` for usage and examples.

#![cfg_attr(docsrs, feature(doc_cfg))]
#![forbid(unsafe_code)]

/// Crate version helpers.
pub mod version;

/// Error types used across the SDK.
pub mod error;

/// Core chain models (Tx, Receipt, Block, Head, etc.).
pub mod types;

/// Minimal ABI model + validation helpers.
pub mod abi;

/// Utility modules (bytes/keccak/sha3/CBOR/bech32).
pub mod utils {
    pub mod bytes;
    pub mod hash;
    pub mod cbor;
    pub mod bech32;
}

/// Address codec and helpers (bech32m `anim1…`).
pub mod address;

/// Transaction pipeline: builders, encoding, sending.
pub mod tx {
    pub mod build;
    pub mod encode;
    pub mod send;
}

/// RPC clients (HTTP/WS). Implementations are feature-gated in the module files.
pub mod rpc {
    pub mod http;
    pub mod ws;
}

/// Wallet: mnemonic, keystore, PQ signer wrappers (feature `pq` optional).
pub mod wallet {
    pub mod mnemonic;
    pub mod keystore;
    pub mod signer;
}

/// High-level contract helpers: generic ABI client, deployer, events, codegen.
pub mod contracts {
    pub mod client;
    pub mod deployer;
    pub mod events;
    pub mod codegen;
}

/// Data Availability client.
pub mod da {
    pub mod client;
}

/// AI Compute Fund client.
pub mod aicf {
    pub mod client;
}

/// Randomness beacon client.
pub mod randomness {
    pub mod client;
}

/// Light verification utilities (headers + DA light proofs).
pub mod light_client {
    pub mod verify;
}

/// Proof helper modules (dev tools / assemblers).
pub mod proofs {
    pub mod hashshare;
    pub mod ai;
    pub mod quantum;
}

/// Bundled schema strings generated by `build.rs`.
///
/// These are optional and may contain `"{}"` placeholders when the repository
/// layout with `sdk/common/schemas/` is not present. Use `HAS_BUNDLED_SCHEMAS`
/// to check whether real schema contents were embedded.
pub mod bundled_schemas {
    include!(concat!(env!("OUT_DIR"), "/schemas.rs"));
}

/// Convenient re-exports for common types.
pub mod prelude {
    pub use crate::address::*;
    pub use crate::contracts::{client::ContractClient, deployer::Deployer};
    pub use crate::error::*;
    pub use crate::rpc::{http::Client as HttpClient, ws::WsClient};
    pub use crate::tx::{build, encode};
    pub use crate::types::*;
}

