"use client";
import { useEffect, useRef, useState } from "react";

interface Msg {
  id: string;
  role: "user" | "assistant" | "tool" | "system";
  content: string;
  toolName?: string;
  source?: string;
  provider?: string;
  // The actual miner that ran inference (bech32 id), distinct from the
  // routing-layer name in `provider`. Surfaced as "served by anim1abc…"
  // so the receipt feels like a real AICF chat session, not an opaque
  // server-mediated request.
  minerId?: string | null;
  jobId?: string | null;
  tier?: string;
  requestedTier?: string;
  costAnm?: number;
  latencyMs?: number;
  fallbackReasons?: string[];
  errored?: boolean;
}

interface ToolChip {
  id: string;
  label: string;
  emoji: string;
  description: string;
}

const TOOL_CHIPS: ToolChip[] = [
  { id: "chain_head",     emoji: "📡", label: "Chain head",      description: "current tip height + hash" },
  { id: "recent_blocks",  emoji: "📦", label: "Last 5 blocks",   description: "block list, newest first" },
  { id: "recent_jobs",    emoji: "🧠", label: "AI jobs",         description: "recent aicf.work jobs" },
  { id: "list_workers",   emoji: "⚙️", label: "Workers",         description: "registered miners" },
  { id: "da_status",      emoji: "💾", label: "DA status",       description: "blob store stats" },
  { id: "da_namespaces",  emoji: "🏷️", label: "DA namespaces",   description: "active namespaces" },
  { id: "network_stats",  emoji: "📊", label: "Network",         description: "hashrate + tip" },
];

const SUGGESTED_PROMPTS = [
  "What is Animica in one sentence?",
  "How do I run a miner?",
  "What's the difference between DA and useful-work jobs?",
  "Explain post-quantum signatures briefly.",
  "How much does an LLM inference cost?",
];

const TIERS = ["tiny", "standard", "premium", "xl"] as const;
type Tier = (typeof TIERS)[number];

const WELCOME: Msg = {
  id: "welcome",
  role: "assistant",
  content: [
    "Welcome to **Animica**. Every reply is generated by a real miner on the live network — quote, pay, submit, stream, settle, all on-chain. Each turn shows a green **live AICF miner** tag plus the tier, cost in ANM, and latency. Click **receipt ↗** to see which miner served the turn and the AICF job id.",
    "",
    "Ask anything about the chain, or hit a tool chip below to fetch live on-chain data.",
  ].join("\n"),
};

export function LandingChat() {
  const [messages, setMessages] = useState<Msg[]>([WELCOME]);
  const [input, setInput] = useState("");
  const [tier, setTier] = useState<Tier>("tiny");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const endRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages.length, busy]);

  async function sendChat(text: string) {
    const userMsg: Msg = { id: crypto.randomUUID(), role: "user", content: text };
    const next = [...messages, userMsg];
    setMessages(next);
    setInput("");
    setBusy(true);
    setErr(null);
    try {
      const wire = next.filter((m) => m.id !== "welcome").map((m) => ({
        role: m.role === "tool" ? "tool" : m.role,
        content: m.toolName
          ? `[tool:${m.toolName}]\n${m.content}`
          : m.content,
      }));
      const res = await fetch("/api/landing-chat", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ messages: wire, tier }),
      });
      const data = await safeJson(res);
      if (!res.ok || !data.ok) {
        const message = data.error ??
          (data._nonJson
            ? `The server returned a ${res.status} ${res.statusText || ""} HTML page — usually a timeout. The AICF miners often take 30-60s for a chat turn; please retry.`
            : `HTTP ${res.status}`);
        setErr(message);
        setMessages((m) => [...m, {
          id: crypto.randomUUID(), role: "assistant",
          content: message,
          errored: true,
        }]);
        return;
      }
      setMessages((m) => [...m, {
        id: crypto.randomUUID(),
        role: "assistant",
        content: String(data.content || ""),
        source: data.source,
        provider: data.provider,
        minerId: data.minerId ?? null,
        jobId: data.jobId ?? null,
        tier: data.tier,
        requestedTier: data.requestedTier,
        costAnm: data.costAnm,
        latencyMs: data.latencyMs,
        fallbackReasons: Array.isArray(data.fallbackReasons) ? data.fallbackReasons : [],
      }]);
    } catch (e: any) {
      setErr(e?.message ?? "network error");
    } finally {
      setBusy(false);
    }
  }

  async function invokeTool(chip: ToolChip) {
    setBusy(true);
    setErr(null);
    // Immediately show a placeholder so the user sees the chip click.
    const placeholderId = crypto.randomUUID();
    setMessages((m) => [...m, {
      id: placeholderId,
      role: "tool",
      toolName: chip.id,
      content: `Calling \`${chip.id}\`…`,
    }]);
    try {
      const res = await fetch("/api/landing-chat", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ toolCall: { tool: chip.id } }),
      });
      const data = await safeJson(res);
      setMessages((m) => m.map((msg) => msg.id === placeholderId ? {
        ...msg,
        content: data.content
          || data.error
          || (data._nonJson
              ? `Server returned ${res.status} HTML (likely a timeout). Try again.`
              : "(no result)"),
        errored: !data.ok,
      } : msg));
    } catch (e: any) {
      setMessages((m) => m.map((msg) => msg.id === placeholderId ? {
        ...msg,
        content: `Failed: ${e?.message ?? e}`,
        errored: true,
      } : msg));
    } finally {
      setBusy(false);
    }
  }

  function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    const text = input.trim();
    if (!text || busy) return;
    sendChat(text);
  }

  function onKeyDown(e: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      onSubmit(e as any);
    }
  }

  return (
    <div className="mx-auto flex h-full max-w-3xl flex-col gap-4 px-4 pb-6 pt-4">
      {/* Header */}
      <header className="flex flex-wrap items-baseline justify-between gap-3">
        <div className="flex items-baseline gap-3">
          <div className="text-xl font-semibold text-slate-100">Animica</div>
          <div className="hidden text-[11px] text-slate-500 md:block">
            chat live with a network miner · post-quantum L1 for useful AI work
          </div>
        </div>
        <div className="flex items-center gap-2 text-[11px]">
          <span className="text-slate-500">tier:</span>
          <select
            value={tier}
            onChange={(e) => setTier(e.target.value as Tier)}
            disabled={busy}
            className="rounded-md border border-slate-700 bg-slate-900 px-2 py-1 font-mono text-slate-200 focus:border-indigo-500 focus:outline-none disabled:opacity-60"
          >
            {TIERS.map((t) => <option key={t} value={t}>{t}</option>)}
          </select>
          <a
            href="https://pypi.org/project/animica/"
            target="_blank" rel="noreferrer"
            className="ml-2 rounded-md border border-slate-700 bg-slate-900 px-2 py-1 text-slate-300 hover:border-slate-600"
            title="Same thing in your terminal"
          >
            CLI ↗
          </a>
        </div>
      </header>

      {/* Message stream */}
      <main className="flex flex-1 flex-col gap-3 overflow-y-auto rounded-2xl border border-slate-800 bg-slate-950/40 p-4">
        {messages.map((m) => <MessageBubble key={m.id} msg={m} />)}
        {busy ? (
          <div className="text-xs text-slate-500">
            <span className="inline-block animate-pulse">●●●</span>
          </div>
        ) : null}
        <div ref={endRef} />
      </main>

      {/* Tool chips */}
      <div className="flex flex-wrap gap-1.5">
        {TOOL_CHIPS.map((chip) => (
          <button
            key={chip.id}
            type="button"
            onClick={() => invokeTool(chip)}
            disabled={busy}
            title={chip.description}
            className="rounded-full border border-slate-700 bg-slate-900/60 px-3 py-1 text-xs text-slate-200 hover:border-indigo-500 hover:bg-slate-900 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <span className="mr-1">{chip.emoji}</span>{chip.label}
          </button>
        ))}
      </div>

      {/* Input */}
      <form onSubmit={onSubmit} className="flex flex-col gap-2">
        <div className="flex items-end gap-2 rounded-2xl border border-slate-800 bg-slate-900/40 p-2 focus-within:border-indigo-500">
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={onKeyDown}
            disabled={busy}
            rows={1}
            placeholder="Ask anything · Shift+Enter for newline"
            className="max-h-40 flex-1 resize-none bg-transparent px-2 py-1 text-sm text-slate-100 placeholder:text-slate-500 focus:outline-none disabled:opacity-50"
          />
          <button
            type="submit"
            disabled={!input.trim() || busy}
            className="rounded-lg bg-indigo-500 px-3 py-1.5 text-sm font-medium text-white hover:bg-indigo-400 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Send
          </button>
        </div>

        {/* Suggested prompts (only when no user turns yet) */}
        {messages.filter((m) => m.role === "user").length === 0 ? (
          <div className="flex flex-wrap gap-1.5">
            {SUGGESTED_PROMPTS.map((p) => (
              <button
                key={p}
                type="button"
                onClick={() => sendChat(p)}
                disabled={busy}
                className="rounded-full bg-slate-900/60 px-3 py-1 text-xs text-slate-400 hover:text-slate-100 disabled:opacity-50"
              >
                {p}
              </button>
            ))}
          </div>
        ) : null}

        {err ? <p className="text-xs text-rose-400">{err}</p> : null}
        <p className="text-center text-[10px] text-slate-600">
          Each reply costs a fraction of an ANM paid to the worker that served it · live network · no signup
        </p>
      </form>
    </div>
  );
}

function MessageBubble({ msg }: { msg: Msg }) {
  if (msg.role === "user") {
    return (
      <div className="flex justify-end">
        <div className="max-w-[80%] rounded-2xl rounded-br-sm bg-indigo-500/90 px-4 py-2 text-sm text-white whitespace-pre-wrap">
          {msg.content}
        </div>
      </div>
    );
  }
  if (msg.role === "tool") {
    return (
      <div className="flex justify-start">
        <div className={`flex max-w-[90%] flex-col gap-1 rounded-2xl rounded-bl-sm border px-4 py-2 text-xs ${
          msg.errored
            ? "border-rose-700/40 bg-rose-950/30 text-rose-200"
            : "border-emerald-700/40 bg-emerald-950/30 text-emerald-100"
        }`}>
          <span className="text-[10px] uppercase tracking-wider opacity-60">
            tool · {msg.toolName}
          </span>
          <div className="whitespace-pre-wrap font-mono leading-relaxed">
            <Markdownish text={msg.content} />
          </div>
        </div>
      </div>
    );
  }
  // assistant
  return (
    <div className="flex justify-start">
      <div className="flex max-w-[90%] flex-col gap-1">
        <div className={`rounded-2xl rounded-bl-sm border px-4 py-2 text-sm leading-relaxed ${
          msg.errored
            ? "border-rose-700/40 bg-rose-950/30 text-rose-200"
            : "border-slate-700/60 bg-slate-900/60 text-slate-100"
        }`}>
          <Markdownish text={msg.content} />
        </div>
        {(msg.source || msg.costAnm != null || msg.latencyMs != null) ? (
          <AicfReceipt msg={msg} />
        ) : null}
      </div>
    </div>
  );
}

// Very small markdown subset: **bold**, `code`, lists, line breaks.
function Markdownish({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <>
      {lines.map((line, i) => {
        // List item
        if (/^\s*[-*]\s+/.test(line)) {
          return (
            <div key={i} className="ml-3 before:mr-1 before:content-['•']">
              {renderInline(line.replace(/^\s*[-*]\s+/, ""))}
            </div>
          );
        }
        if (line.trim() === "") return <br key={i} />;
        return <div key={i}>{renderInline(line)}</div>;
      })}
    </>
  );
}

function renderInline(s: string): React.ReactNode {
  // Tokenize **bold** and `code` and #headers
  const parts: React.ReactNode[] = [];
  let i = 0;
  let idx = 0;
  while (i < s.length) {
    if (s.startsWith("**", i)) {
      const end = s.indexOf("**", i + 2);
      if (end > i) {
        parts.push(<strong key={idx++} className="font-semibold text-white">{s.slice(i + 2, end)}</strong>);
        i = end + 2;
        continue;
      }
    }
    if (s[i] === "`") {
      const end = s.indexOf("`", i + 1);
      if (end > i) {
        parts.push(<code key={idx++} className="rounded bg-slate-950 px-1 font-mono text-[12px] text-slate-200">{s.slice(i + 1, end)}</code>);
        i = end + 1;
        continue;
      }
    }
    // Accumulate plain text up to the next markdown sigil
    let j = i;
    while (j < s.length && s[j] !== "`" && !s.startsWith("**", j)) j++;
    if (j > i) {
      parts.push(<span key={idx++}>{s.slice(i, j)}</span>);
      i = j;
    } else {
      i++;
    }
  }
  return <>{parts}</>;
}

/**
 * Receipt rendered under every assistant turn so the UI feels like a
 * real AICF chat session ("paid X ANM to miner Y, AICF job 0xZ…")
 * instead of an opaque proxy. The compact tag row stays even when the
 * extended panel is collapsed so scanning the transcript still surfaces
 * the source / tier / cost / latency at a glance.
 */
function AicfReceipt({ msg }: { msg: Msg }) {
  const [open, setOpen] = useState(false);
  const isLive = msg.source === "aicf";
  const fallbackCount = msg.fallbackReasons?.length ?? 0;
  return (
    <div className="flex flex-col gap-1 px-1">
      <div className="flex flex-wrap items-center gap-2 text-[10px] text-slate-500">
        {msg.source ? (
          <span className={`rounded-full px-1.5 py-0.5 ${
            isLive                       ? "bg-emerald-900/40 text-emerald-300" :
            msg.source === "modal"       ? "bg-sky-900/40 text-sky-300" :
                                            "bg-slate-800 text-slate-400"
          }`}>
            {isLive ? "live AICF miner" :
             msg.source === "modal" ? "modal" :
                                       "local stub"}
          </span>
        ) : null}
        {msg.tier ? <span>tier <span className="font-mono">{msg.tier}</span></span> : null}
        {msg.costAnm != null ? (
          <span>
            <span className="font-mono">{msg.costAnm.toFixed(6)}</span> ANM
          </span>
        ) : null}
        {msg.latencyMs != null ? (
          <span><span className="font-mono">{(msg.latencyMs / 1000).toFixed(1)}</span>s</span>
        ) : null}
        {fallbackCount > 0 ? (
          <span className="rounded-full bg-amber-900/40 px-1.5 py-0.5 text-amber-300">
            {fallbackCount} fallback{fallbackCount === 1 ? "" : "s"}
          </span>
        ) : null}
        {(msg.minerId || msg.jobId) ? (
          <button
            type="button"
            onClick={() => setOpen((v) => !v)}
            className="rounded-full bg-slate-800 px-1.5 py-0.5 text-slate-300 hover:bg-slate-700"
            title="Show / hide the AICF receipt for this turn"
          >
            {open ? "hide receipt" : "receipt ↗"}
          </button>
        ) : null}
      </div>
      {open && (msg.minerId || msg.jobId) ? (
        <div className="rounded-md border border-emerald-700/30 bg-emerald-950/20 p-2 text-[10px] text-slate-300">
          <div className="text-[9px] uppercase tracking-wider text-emerald-300/80 mb-1">
            on-chain AICF receipt
          </div>
          {msg.minerId ? (
            <div className="flex gap-2">
              <span className="w-16 text-slate-500">miner</span>
              <code className="break-all text-slate-200">{msg.minerId}</code>
            </div>
          ) : null}
          {msg.jobId ? (
            <div className="flex gap-2">
              <span className="w-16 text-slate-500">job</span>
              <code className="break-all text-slate-200">{msg.jobId}</code>
            </div>
          ) : null}
          {msg.requestedTier && msg.tier && msg.requestedTier !== msg.tier ? (
            <div className="flex gap-2">
              <span className="w-16 text-slate-500">tier</span>
              <span className="text-slate-300">
                requested <span className="font-mono">{msg.requestedTier}</span> →
                served <span className="font-mono">{msg.tier}</span>
              </span>
            </div>
          ) : null}
          {fallbackCount > 0 ? (
            <div className="flex gap-2">
              <span className="w-16 text-slate-500">fallbacks</span>
              <span className="text-amber-200">{msg.fallbackReasons!.join(", ")}</span>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

/**
 * Read a response body and parse JSON safely. If the body isn't JSON
 * (typical case: the route timed out and the platform served an HTML
 * 502/504 page, which used to surface as the V8 error
 * "Unexpected token '<', \"<html>...\"" verbatim to the user), return
 * a synthesized envelope marked with _nonJson so callers can show a
 * humane message instead.
 */
async function safeJson(res: Response): Promise<any> {
  const raw = await res.text();
  const ct = (res.headers.get("content-type") || "").toLowerCase();
  if (!ct.includes("application/json") && /^\s*<(?:!doctype|html|head)/i.test(raw)) {
    return { ok: false, _nonJson: true, _bodyPreview: raw.slice(0, 200) };
  }
  try {
    return JSON.parse(raw);
  } catch {
    return { ok: false, _nonJson: true, _bodyPreview: raw.slice(0, 200) };
  }
}
