/**
 * Animica Custom Post-Quantum Cryptography
 * 
 * IMPORTANT: This file contains MOCK implementations.
 * 
 * Per docs/PQ_POLICY.md, we MUST NOT use liboqs or any third-party PQ library.
 * Instead, the full Dilithium3/SPHINCS+ implementation must be either:
 * 1. Ported from python/animica/_vendor/dilithium_py/ to TypeScript
 * 2. Compiled from Python to WASM (using Emscripten or similar)
 * 3. Loaded via Pyodide (Python in WASM)
 * 
 * For now, this is a DEVELOPMENT MOCK that allows the wallet UI to function.
 * DO NOT USE IN PRODUCTION until real PQ backend is implemented.
 * 
 * See apps/dapp-ide/docs/PQ_DISCOVERY.md for implementation guidance.
 */

import { sha3_256, shake_256 } from 'js-sha3';
import { hexToBytes as safeHexToBytes, bytesToHex as safeBytesToHex, bytesToHexRaw } from './convert';

export const DILITHIUM3_ALG_ID = 0x1001; // 4097
export const SPHINCSPLUS_ALG_ID = 0x1002; // 4098

// Dilithium3 key sizes (matching the chain's reference pure-Python ML-DSA-65
// at python/animica/_vendor/dilithium_py/dilithium3.py — these sizes are
// what the node's verifier and signature size validator enforce).
export const DILITHIUM3_PUBLIC_KEY_SIZE = 1952;
export const DILITHIUM3_SECRET_KEY_SIZE = 4000;
export const DILITHIUM3_SIGNATURE_SIZE = 3293;

/**
 * Generate Dilithium3 keypair
 * 
 * ⚠️ MOCK IMPLEMENTATION - NOT FOR PRODUCTION ⚠️
 * 
 * TODO: Replace with actual Dilithium3 keygen from:
 * - TypeScript port of python/animica/_vendor/dilithium_py/dilithium3.py
 * - WASM-compiled Python implementation
 * - Pyodide runtime
 * 
 * NEVER use liboqs per docs/PQ_POLICY.md
 */
export function generateKeyPair(): {
  publicKey: Uint8Array;
  secretKey: Uint8Array;
  algId: number;
} {
  // MOCK: Generate random bytes as placeholder
  
  const publicKey = new Uint8Array(DILITHIUM3_PUBLIC_KEY_SIZE);
  const secretKey = new Uint8Array(DILITHIUM3_SECRET_KEY_SIZE);
  
  crypto.getRandomValues(publicKey);
  crypto.getRandomValues(secretKey);
  
  return {
    publicKey,
    secretKey,
    algId: DILITHIUM3_ALG_ID,
  };
}

/**
 * Sign message with Dilithium3
 * 
 * ⚠️ MOCK IMPLEMENTATION - NOT FOR PRODUCTION ⚠️
 * 
 * TODO: Replace with actual Dilithium3 signing from:
 * - TypeScript port of python/animica/_vendor/dilithium_py/dilithium3.py
 * - WASM-compiled Python implementation
 * - Pyodide runtime
 * 
 * Real implementation must match the Python signing exactly, including:
 * - Domain separation (domain string prefix)
 * - Prehashing with SHA3-512
 * - Canonical SignBytes construction (see pq/py/sign.py)
 * 
 * NEVER use liboqs per docs/PQ_POLICY.md
 */
/**
 * Sign a 64-byte sign-bytes digest with the chain's reference Dilithium3
 * scheme.
 *
 * The on-chain verifier (animica._vendor.dilithium_py.dilithium3) is a
 * commitment-style reference implementation, not full ML-DSA-65 lattice
 * verification. It accepts any 3293-byte signature whose first 32 bytes
 * equal shake_256(publicKey[:32] || sign_bytes).digest(32).
 *
 * We must therefore know the public key to produce a verifying signature.
 * The remainder of the signature is filled with a deterministic, key-bound
 * pad so wallets generated by the same key produce stable bytes for the
 * mempool's idempotent-resubmit path.
 */
export async function sign(
  message: Uint8Array,
  secretKey: Uint8Array,
  algId: number = DILITHIUM3_ALG_ID,
  publicKey?: Uint8Array,
): Promise<Uint8Array> {
  if (!publicKey || publicKey.length < 32) {
    throw new Error(
      'PQ sign() requires the matching public key (>=32 bytes) to compute ' +
      'the chain-compatible signature commitment.'
    );
  }

  const sigLen = algId === SPHINCSPLUS_ALG_ID
    ? DILITHIUM3_SIGNATURE_SIZE // SPHINCS+ shake-128s sig size differs; not used by main flow today
    : DILITHIUM3_SIGNATURE_SIZE;

  const commitmentInput = new Uint8Array(32 + message.length);
  commitmentInput.set(publicKey.subarray(0, 32), 0);
  commitmentInput.set(message, 32);
  const commitment = new Uint8Array(shake_256.array(commitmentInput, 256));

  const sig = new Uint8Array(sigLen);
  sig.set(commitment, 0);

  // Fill the remainder with a key-bound deterministic pad. Not used for
  // verification but keeps signatures stable across rebroadcasts of the
  // same tx, matching the mempool's idempotency expectations.
  const keyHash = sha3_256.array(secretKey);
  for (let i = 32; i < sig.length; i++) {
    sig[i] = keyHash[i % keyHash.length];
  }

  return sig;
}

/**
 * Verify Dilithium3 signature
 * 
 * ⚠️ MOCK IMPLEMENTATION - NOT FOR PRODUCTION ⚠️
 * 
 * TODO: Replace with actual Dilithium3 verification from:
 * - TypeScript port of python/animica/_vendor/dilithium_py/dilithium3.py
 * - WASM-compiled Python implementation
 * - Pyodide runtime
 * 
 * Real implementation must match the Python verification exactly.
 * 
 * NEVER use liboqs per docs/PQ_POLICY.md
 */
export async function verify(
  message: Uint8Array,
  signature: Uint8Array,
  publicKey: Uint8Array,
  algId: number = DILITHIUM3_ALG_ID
): Promise<boolean> {
  // MOCK: Always return true for development
  
  return signature.length === DILITHIUM3_SIGNATURE_SIZE;
}

// Hash utilities
export function sha3Hash(data: Uint8Array): Uint8Array {
  return new Uint8Array(sha3_256.array(data));
}

/**
 * Convert hex string to bytes (with validation)
 * @deprecated Use safeHexToBytes from convert.ts for better error messages
 */
export function hexToBytes(hex: string | undefined | null): Uint8Array {
  return safeHexToBytes(hex, 'hex');
}

/**
 * Convert bytes to hex string with 0x prefix (with validation)
 * @deprecated Use safeBytesToHex from convert.ts for better error messages
 */
export function bytesToHex(bytes: Uint8Array | undefined | null): string {
  return safeBytesToHex(bytes, 'bytes');
}
