#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Animica Explorer API Entrypoint
# - Renders /etc/animica/explorer.toml from environment variables
# - Waits for the node RPC to be ready
# - Starts the Explorer HTTP API (used by explorer-web)
#
# Environment (override at runtime):
#   RPC_URL=http://node:8545
#   WS_URL=ws://node:8545/ws
#   CHAIN_ID=1
#
#   EXPLORER_HOST=0.0.0.0
#   EXPLORER_PORT=8080
#   EXPLORER_CORS=*,http://localhost:5174
#   EXPLORER_RATE_LIMITS=default
#   EXPLORER_LOG_LEVEL=info          # debug|info|warn|error
#   EXPLORER_LOG_FORMAT=json         # json|text
#
#   EXPLORER_DB_BACKEND=sqlite       # sqlite|rocksdb (sqlite default)
#   EXPLORER_SQLITE_FILE=explorer.db
#   EXPLORER_ROCKS_DIR=explorer_rocks
#   EXPLORER_CACHE_DIR=/data/cache
#
#   HEAD_CACHE_TTL=3s                # lightweight cache TTLs
#   BLOCK_CACHE_TTL=5s
#   TX_CACHE_TTL=5s
#
#   METRICS_ENABLE=true
#   METRICS_HOST=0.0.0.0
#   METRICS_PORT=9109
#
#   STARTUP_WAIT_SECS=90
#   EXPLORER_APP=explorer.api:app    # override if module path differs
#   UVICORN_WORKERS=1
# ------------------------------------------------------------------------------

set -eu

# ---- defaults ---------------------------------------------------------------
: "${RPC_URL:=http://127.0.0.1:8545}"
: "${WS_URL:=ws://127.0.0.1:8545/ws}"
: "${CHAIN_ID:=1}"

: "${EXPLORER_HOST:=0.0.0.0}"
: "${EXPLORER_PORT:=8080}"
: "${EXPLORER_CORS:=*}"
: "${EXPLORER_RATE_LIMITS:=default}"
: "${EXPLORER_LOG_LEVEL:=info}"
: "${EXPLORER_LOG_FORMAT:=json}"

: "${EXPLORER_DB_BACKEND:=sqlite}"
: "${EXPLORER_SQLITE_FILE:=explorer.db}"
: "${EXPLORER_ROCKS_DIR:=explorer_rocks}"
: "${EXPLORER_CACHE_DIR:=/data/cache}"

: "${HEAD_CACHE_TTL:=3s}"
: "${BLOCK_CACHE_TTL:=5s}"
: "${TX_CACHE_TTL:=5s}"

: "${METRICS_ENABLE:=true}"
: "${METRICS_HOST:=0.0.0.0}"
: "${METRICS_PORT:=9109}"

: "${STARTUP_WAIT_SECS:=90}"
: "${EXPLORER_APP:=explorer.api:app}"
: "${UVICORN_WORKERS:=1}"

CONFIG_PATH="/etc/animica/explorer.toml"
mkdir -p "$(dirname "${CONFIG_PATH}")" "${EXPLORER_CACHE_DIR}" /data

# ---- helpers ----------------------------------------------------------------
comma_to_toml_array() {
  v="$1"
  if [ -z "${v}" ]; then printf '[]'; return; fi
  v=$(printf "%s" "${v}" | sed 's/ *, */,/g')
  IFS=','; set -- ${v}; unset IFS
  printf '['
  first=1
  for item in "$@"; do
    s="${item}"
    if [ "${first}" -eq 0 ]; then printf ', '; fi
    printf '"%s"' "${s}"
    first=0
  done
  printf ']'
}

bool_to_toml() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|on|ON)  printf 'true' ;;
    *)                               printf 'false' ;;
  esac
}

wait_for_http() {
  url="$1"; timeout="${2:-60}"
  echo ">> Waiting for ${url} (timeout ${timeout}s)…"
  i=0
  while [ "${i}" -lt "${timeout}" ]; do
    if command -v wget >/dev/null 2>&1; then
      if wget -q -O /dev/null "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"; return 0
      fi
    elif command -v curl >/dev/null 2>&1; then
      if curl -fsS "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"; return 0
      fi
    fi
    i=$((i+1))
    sleep 1
  done
  echo "ERROR: timed out waiting for ${url}" >&2
  return 1
}

# ---- derive DB URI -----------------------------------------------------------
case "${EXPLORER_DB_BACKEND}" in
  sqlite)
    DB_FILE="/data/${EXPLORER_SQLITE_FILE}"
    DB_URI="sqlite:///${DB_FILE}"
    ;;
  rocksdb|rocks)
    DB_DIR="/data/${EXPLORER_ROCKS_DIR}"
    mkdir -p "${DB_DIR}"
    DB_URI="rocksdb://${DB_DIR}"
    ;;
  *)
    echo "ERROR: Unsupported EXPLORER_DB_BACKEND='${EXPLORER_DB_BACKEND}'" >&2
    exit 2
    ;;
esac

# ---- render config -----------------------------------------------------------
echo ">> Rendering ${CONFIG_PATH}"
{
  echo '# Autogenerated by entrypoints/explorer.sh'
  echo ''
  echo '[server]'
  printf 'host = "%s"\n' "${EXPLORER_HOST}"
  printf 'port = %s\n' "${EXPLORER_PORT}"
  printf 'cors_allowlist = ' ; comma_to_toml_array "${EXPLORER_CORS}"; echo
  printf 'rate_limits = "%s"\n' "${EXPLORER_RATE_LIMITS}"
  echo ''
  echo '[logging]'
  printf 'level = "%s"\n' "${EXPLORER_LOG_LEVEL}"
  printf 'format = "%s"\n' "${EXPLORER_LOG_FORMAT}"
  echo ''
  echo '[rpc]'
  printf 'url = "%s"\n' "${RPC_URL}"
  printf 'ws_url = "%s"\n' "${WS_URL}"
  printf 'chain_id = %s\n' "${CHAIN_ID}"
  echo ''
  echo '[storage]'
  printf 'db_uri = "%s"\n' "${DB_URI}"
  printf 'cache_dir = "%s"\n' "${EXPLORER_CACHE_DIR}"
  echo ''
  echo '[cache]'
  printf 'head_ttl = "%s"\n' "${HEAD_CACHE_TTL}"
  printf 'block_ttl = "%s"\n' "${BLOCK_CACHE_TTL}"
  printf 'tx_ttl = "%s"\n' "${TX_CACHE_TTL}"
  echo ''
  echo '[metrics]'
  printf 'enable = %s\n' "$(bool_to_toml "${METRICS_ENABLE}")"
  printf 'host = "%s"\n' "${METRICS_HOST}"
  printf 'port = %s\n' "${METRICS_PORT}"
} > "${CONFIG_PATH}"

export ANIMICA_EXPLORER_CONFIG="${CONFIG_PATH}"
echo ">> ANIMICA_EXPLORER_CONFIG=${ANIMICA_EXPLORER_CONFIG}"

# ---- readiness ---------------------------------------------------------------
if ! wait_for_http "${RPC_URL%/}/readyz" "${STARTUP_WAIT_SECS}"; then
  echo ">> Falling back to ${RPC_URL%/}/healthz"
  wait_for_http "${RPC_URL%/}/healthz" "${STARTUP_WAIT_SECS}" || true
fi

# ---- start server ------------------------------------------------------------
echo ">> Starting Explorer API (${EXPLORER_APP}) on ${EXPLORER_HOST}:${EXPLORER_PORT}"
if command -v uvicorn >/dev/null 2>&1; then
  exec uvicorn "${EXPLORER_APP}" --host "${EXPLORER_HOST}" --port "${EXPLORER_PORT}" --workers "${UVICORN_WORKERS}"
else
  # Fallbacks if uvicorn isn't available in the image
  case "${EXPLORER_APP}" in
    *:app)
      # Try running the module directly
      mod="${EXPLORER_APP%:*}"
      echo ">> uvicorn not found; trying 'python -m ${mod}'"
      exec python -m "${mod}"
      ;;
    *)
      echo "ERROR: uvicorn not installed and EXPLORER_APP is not module:app" >&2
      exit 3
      ;;
  esac
fi
