#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Animica Miner Entrypoint
# - Renders /etc/animica/miner.toml from env
# - Waits for local node RPC to be ready
# - Starts the built-in CPU/GPU miner (HashShare + optional useful proofs workers)
#
# Key env (override at runtime):
#   RPC_URL=http://node:8545              # JSON-RPC base URL
#   WS_URL=ws://node:8545/ws              # WebSocket URL (subscriptions/getwork)
#   CHAIN_ID=1
#
#   MINER_DEVICE=cpu                      # cpu|cuda|rocm|opencl|metal
#   MINER_THREADS=auto                    # auto → CPU count, else integer
#   MINER_SHARE_TARGET=auto               # "auto" (follows Θ) or micro-target number
#   MINER_LOG_LEVEL=info                  # debug|info|warn|error
#
#   ENABLE_AI_WORKER=false                # enqueue tiny AI jobs to AICF for devnet demos
#   ENABLE_QUANTUM_WORKER=false           # enqueue tiny quantum trap jobs
#   ENABLE_STORAGE_WORKER=false           # storage heartbeat worker
#   ENABLE_VDF_WORKER=true                # local VDF prover for bonus
#
#   STRATUM_PROXY_ENABLE=false            # run a stratum proxy in-process (optional)
#   STRATUM_LISTEN=0.0.0.0:3333
#
#   STARTUP_WAIT_SECS=90                  # max wait for RPC readiness
# ------------------------------------------------------------------------------

set -eu

# ---- defaults ---------------------------------------------------------------
: "${RPC_URL:=http://127.0.0.1:8545}"
: "${WS_URL:=ws://127.0.0.1:8545/ws}"
: "${CHAIN_ID:=1}"

: "${MINER_DEVICE:=cpu}"
: "${MINER_THREADS:=auto}"
: "${MINER_SHARE_TARGET:=auto}"
: "${MINER_LOG_LEVEL:=info}"

: "${ENABLE_AI_WORKER:=false}"
: "${ENABLE_QUANTUM_WORKER:=false}"
: "${ENABLE_STORAGE_WORKER:=false}"
: "${ENABLE_VDF_WORKER:=true}"

: "${STRATUM_PROXY_ENABLE:=false}"
: "${STRATUM_LISTEN:=0.0.0.0:3333}"

: "${STARTUP_WAIT_SECS:=90}"

CONFIG_PATH="/etc/animica/miner.toml"
mkdir -p "$(dirname "${CONFIG_PATH}")"

# ---- helpers ----------------------------------------------------------------
bool_to_toml() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|on|ON)  printf 'true' ;;
    *)                               printf 'false' ;;
  esac
}

cpu_count() {
  if command -v nproc >/dev/null 2>&1; then
    nproc
  elif [ -r /proc/cpuinfo ]; then
    awk '/^processor/{n+=1} END{print (n?n:1)}' /proc/cpuinfo
  elif command -v sysctl >/dev/null 2>&1; then
    sysctl -n hw.ncpu 2>/dev/null || echo 1
  else
    echo 1
  fi
}

wait_for_http() {
  url="$1"; timeout="${2:-60}"
  echo ">> Waiting for ${url} (timeout ${timeout}s)…"
  i=0
  while [ "${i}" -lt "${timeout}" ]; do
    if command -v wget >/dev/null 2>&1; then
      if wget -q -O /dev/null "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"
        return 0
      fi
    elif command -v curl >/dev/null 2>&1; then
      if curl -fsS "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"
        return 0
      fi
    fi
    i=$((i+1))
    sleep 1
  done
  echo "ERROR: timed out waiting for ${url}" >&2
  return 1
}

# Resolve thread count
if [ "${MINER_THREADS}" = "auto" ]; then
  MINER_THREADS="$(cpu_count)"
fi

# ---- render TOML ------------------------------------------------------------
echo ">> Rendering ${CONFIG_PATH}"
{
  echo '# Autogenerated by entrypoints/miner.sh'
  echo ''
  echo '[rpc]'
  printf 'url = "%s"\n' "${RPC_URL}"
  printf 'ws_url = "%s"\n' "${WS_URL}"
  printf 'chain_id = %s\n' "${CHAIN_ID}"
  echo ''
  echo '[miner]'
  printf 'device = "%s"\n' "${MINER_DEVICE}"
  printf 'threads = %s\n' "${MINER_THREADS}"
  if [ "${MINER_SHARE_TARGET}" = "auto" ]; then
    echo 'share_target_auto = true'
  else
    echo 'share_target_auto = false'
    printf 'share_target_micro = %s\n' "${MINER_SHARE_TARGET}"
  fi
  printf 'log_level = "%s"\n' "${MINER_LOG_LEVEL}"
  echo ''
  echo '[workers]'
  printf 'ai = %s\n'       "$(bool_to_toml "${ENABLE_AI_WORKER}")"
  printf 'quantum = %s\n'  "$(bool_to_toml "${ENABLE_QUANTUM_WORKER}")"
  printf 'storage = %s\n'  "$(bool_to_toml "${ENABLE_STORAGE_WORKER}")"
  printf 'vdf = %s\n'      "$(bool_to_toml "${ENABLE_VDF_WORKER}")"
  echo ''
  echo '[stratum]'
  printf 'enable = %s\n' "$(bool_to_toml "${STRATUM_PROXY_ENABLE}")"
  printf 'listen = "%s"\n' "${STRATUM_LISTEN}"
} > "${CONFIG_PATH}"

# ---- wait for node readiness -------------------------------------------------
# Try /readyz first (preferred), otherwise /healthz, otherwise a simple RPC call
if ! wait_for_http "${RPC_URL%/}/readyz" "${STARTUP_WAIT_SECS}"; then
  echo ">> Falling back to ${RPC_URL%/}/healthz"
  wait_for_http "${RPC_URL%/}/healthz" "${STARTUP_WAIT_SECS}" || true
fi

# ---- start services ----------------------------------------------------------
# Prefer CLI flags that mirror our config; pass both where reasonable.
# mining/cli/miner.py: `omni miner start --threads N --device cpu --rpc URL --ws WS`
CMD_MINER="python -m mining.cli.miner start \
  --threads ${MINER_THREADS} \
  --device ${MINER_DEVICE} \
  --rpc ${RPC_URL} \
  --ws ${WS_URL}"

# Share target flag if NOT auto
if [ "${MINER_SHARE_TARGET}" != "auto" ]; then
  CMD_MINER="${CMD_MINER} --share-target ${MINER_SHARE_TARGET}"
fi

# Optional workers
if [ "$(bool_to_toml "${ENABLE_AI_WORKER}")" = "true" ]; then
  CMD_MINER="${CMD_MINER} --enable-ai-worker"
fi
if [ "$(bool_to_toml "${ENABLE_QUANTUM_WORKER}")" = "true" ]; then
  CMD_MINER="${CMD_MINER} --enable-quantum-worker"
fi
if [ "$(bool_to_toml "${ENABLE_STORAGE_WORKER}")" = "true" ]; then
  CMD_MINER="${CMD_MINER} --enable-storage-worker"
fi
if [ "$(bool_to_toml "${ENABLE_VDF_WORKER}")" = "false" ]; then
  CMD_MINER="${CMD_MINER} --disable-vdf-worker"
fi

# Optional: run an embedded Stratum proxy for external miners to connect
if [ "$(bool_to_toml "${STRATUM_PROXY_ENABLE}")" = "true" ]; then
  echo ">> Starting Stratum proxy on ${STRATUM_LISTEN}"
  # Run proxy in background; miner will stay in foreground as PID 1
  python -m mining.cli.stratum_proxy --listen "${STRATUM_LISTEN}" --rpc "${RPC_URL}" --ws "${WS_URL}" &
fi

echo ">> Starting miner: ${CMD_MINER}"
# Export config path for libraries that may read it
export ANIMICA_MINER_CONFIG="${CONFIG_PATH}"

# Exec miner in foreground
exec ${CMD_MINER}
