#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Animica Node Entrypoint
# - Renders /etc/animica/node.toml from environment variables
# - Ensures DB is initialized from genesis (for SQLite/RocksDB)
# - Starts the JSON-RPC/WS server (FastAPI via uvicorn)
#
# Exposed knobs (override at runtime):
#   DATA_DIR=/data
#   GENESIS_PATH=/app/core/genesis/genesis.json
#   CHAIN_ID=1
#   DB_BACKEND=sqlite                 # sqlite | rocksdb
#   SQLITE_FILE=animica.db            # only for sqlite backend
#   ROCKS_DIR=rocks                   # only for rocksdb backend (directory under DATA_DIR)
#
#   RPC_HOST=0.0.0.0
#   RPC_PORT=8545
#   RPC_CORS=*,http://localhost:5173  # comma-separated; "*" allowed
#   RPC_RATE_LIMITS=default
#
#   LOG_LEVEL=info                    # debug|info|warn|error
#   LOG_FORMAT=json                   # json|text
#
#   P2P_ENABLE=true
#   P2P_LISTEN=/ip4/0.0.0.0/tcp/30303
#   P2P_SEEDS=                        # comma-separated; optional
#
#   MEMPOOL_ENABLE=true
#   MINER_ENABLE=false
#   RANDOMNESS_ENABLE=true
#   DA_ENABLE=true
#
# Notes:
#  - This script does not supervise multiple processes. It boots the node DB (if needed)
#    and runs the RPC/WS server which wires into core/consensus/p2p via adapters.
# ------------------------------------------------------------------------------

set -eu

# --- defaults -----------------------------------------------------------------
: "${DATA_DIR:=/data}"
: "${GENESIS_PATH:=/app/core/genesis/genesis.json}"
: "${CHAIN_ID:=1}"

: "${DB_BACKEND:=sqlite}"        # sqlite | rocksdb
: "${SQLITE_FILE:=animica.db}"
: "${ROCKS_DIR:=rocks}"

: "${RPC_HOST:=0.0.0.0}"
: "${RPC_PORT:=8545}"
: "${RPC_CORS:=*}"
: "${RPC_RATE_LIMITS:=default}"

: "${LOG_LEVEL:=info}"
: "${LOG_FORMAT:=json}"

: "${P2P_ENABLE:=true}"
: "${P2P_LISTEN:=/ip4/0.0.0.0/tcp/30303}"
: "${P2P_SEEDS:=}"

: "${MEMPOOL_ENABLE:=true}"
: "${MINER_ENABLE:=false}"
: "${RANDOMNESS_ENABLE:=true}"
: "${DA_ENABLE:=true}"

CONFIG_PATH="/etc/animica/node.toml"

mkdir -p "${DATA_DIR}" "$(dirname "${CONFIG_PATH}")"

# --- derive DB URI ------------------------------------------------------------
case "${DB_BACKEND}" in
  sqlite)
    DB_FILE="${DATA_DIR%/}/${SQLITE_FILE}"
    DB_URI="sqlite:///${DB_FILE}"
    ;;
  rocksdb|rocks)
    DB_DIR="${DATA_DIR%/}/${ROCKS_DIR}"
    mkdir -p "${DB_DIR}"
    DB_URI="rocksdb://${DB_DIR}"
    ;;
  *)
    echo "ERROR: Unsupported DB_BACKEND='${DB_BACKEND}' (use 'sqlite' or 'rocksdb')" >&2
    exit 2
    ;;
esac

# --- helpers ------------------------------------------------------------------
comma_to_toml_array() {
  # Turns "a,b,c" into ["a","b","c"]
  # Empty -> []
  # A single "*" -> ["*"]
  v="$1"
  if [ -z "${v}" ]; then
    printf '[]'
    return
  fi
  # Trim spaces around commas
  v=$(printf "%s" "${v}" | sed 's/ *, */,/g')
  IFS=','; set -- ${v}; unset IFS
  printf '['
  first=1
  for item in "$@"; do
    # Preserve literal * (CORS wildcard)
    if [ "${item}" = "*" ]; then
      s='*'
    else
      s="${item}"
    fi
    if [ "${first}" -eq 0 ]; then printf ', '; fi
    printf '"%s"' "${s}"
    first=0
  done
  printf ']'
}

bool_to_toml() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|on|ON)  printf 'true'  ;;
    0|false|FALSE|False|no|NO|off|OFF) printf 'false' ;;
    *) printf 'false' ;;
  esac
}

# --- render TOML --------------------------------------------------------------
echo ">> Rendering ${CONFIG_PATH}"
{
  echo '# Autogenerated by entrypoints/node.sh'
  echo '# Edit environment variables instead of this file.'
  echo ''
  echo '[core]'
  printf 'db_uri = "%s"\n' "${DB_URI}"
  printf 'chain_id = %s\n' "${CHAIN_ID}"
  printf 'genesis_path = "%s"\n' "${GENESIS_PATH}"
  echo ''
  echo '[logging]'
  printf 'level = "%s"\n' "${LOG_LEVEL}"
  printf 'format = "%s"\n' "${LOG_FORMAT}"
  echo ''
  echo '[rpc]'
  printf 'host = "%s"\n' "${RPC_HOST}"
  printf 'port = %s\n' "${RPC_PORT}"
  printf 'rate_limits = "%s"\n' "${RPC_RATE_LIMITS}"
  printf 'cors_allowlist = ' ; comma_to_toml_array "${RPC_CORS}"; echo
  echo ''
  echo '[p2p]'
  printf 'enable = %s\n' "$(bool_to_toml "${P2P_ENABLE}")"
  printf 'listen = "%s"\n' "${P2P_LISTEN}"
  printf 'seeds = ' ; comma_to_toml_array "${P2P_SEEDS}"; echo
  echo ''
  echo '[mempool]'
  printf 'enable = %s\n' "$(bool_to_toml "${MEMPOOL_ENABLE}")"
  echo ''
  echo '[mining]'
  printf 'enable = %s\n' "$(bool_to_toml "${MINER_ENABLE}")"
  echo ''
  echo '[randomness]'
  printf 'enable = %s\n' "$(bool_to_toml "${RANDOMNESS_ENABLE}")"
  echo ''
  echo '[da]'
  printf 'enable = %s\n' "$(bool_to_toml "${DA_ENABLE}")"
  echo ''
  echo '[metrics]'
  echo 'enable = true'
  echo 'host = "0.0.0.0"'
  echo 'port = 9108'
} > "${CONFIG_PATH}"

# --- initialize DB from genesis (idempotent) ----------------------------------
if [ "${DB_BACKEND}" = "sqlite" ]; then
  if [ ! -s "${DB_FILE}" ]; then
    echo ">> Initializing SQLite DB at ${DB_FILE}"
    python -m core.boot --genesis "${GENESIS_PATH}" --db "${DB_URI}" || {
      echo "ERROR: core.boot init failed" >&2; exit 3;
    }
  else
    echo ">> SQLite DB exists at ${DB_FILE} — skipping init"
  fi
else
  # RocksDB: rely on core.boot to be idempotent as well
  if [ ! -f "${DB_DIR}/CURRENT" ]; then
    echo ">> Initializing RocksDB at ${DB_DIR}"
    python -m core.boot --genesis "${GENESIS_PATH}" --db "${DB_URI}" || {
      echo "ERROR: core.boot init (rocksdb) failed" >&2; exit 3;
    }
  else
    echo ">> RocksDB detected at ${DB_DIR} — skipping init"
  fi
fi

export ANIMICA_CONFIG="${CONFIG_PATH}"
echo ">> ANIMICA_CONFIG=${ANIMICA_CONFIG}"

# --- start RPC/WS server ------------------------------------------------------
# Prefer uvicorn to serve rpc.server:app (FastAPI). If rpc/server.py exposes a CLI,
# you could alternatively:  python -m rpc.server
echo ">> Starting RPC server at ${RPC_HOST}:${RPC_PORT}"
exec uvicorn rpc.server:app --host "${RPC_HOST}" --port "${RPC_PORT}" --workers 1
