#!/usr/bin/env sh
# ------------------------------------------------------------------------------
# Animica Studio Services Entrypoint
# - Renders /etc/animica/services.toml from env
# - Optionally migrates the DB on startup
# - Waits for the node RPC to be ready
# - Starts the Studio Services FastAPI (deploy/verify/faucet/artifacts/simulate)
# - (Optional) starts the background verify queue worker
#
# Environment (override as needed):
# Core node
#   RPC_URL=http://node:8545
#   WS_URL=ws://node:8545/ws
#   CHAIN_ID=1
#
# HTTP server
#   SERVICES_HOST=0.0.0.0
#   SERVICES_PORT=8081
#   SERVICES_CORS=*,http://localhost:5173
#   SERVICES_RATE_LIMITS=default        # token-bucket presets string or json-ish
#   SERVICES_LOG_LEVEL=info             # debug|info|warn|error
#   SERVICES_LOG_FORMAT=json            # json|text
#
# Storage
#   SERVICES_DB_BACKEND=sqlite          # sqlite|rocksdb
#   SERVICES_SQLITE_FILE=studio_services.db
#   SERVICES_ROCKS_DIR=studio_services_rocks
#   SERVICES_STORAGE_DIR=/data/services # root for artifacts & temp
#   SERVICES_ARTIFACTS_DIR=/data/services/artifacts
#
# Security
#   SERVICES_API_KEYS=demo123,another   # comma-separated API keys (optional)
#   SERVICES_CORS_ALLOWLIST=*           # same as SERVICES_CORS (alias)
#
# Faucet (optional)
#   FAUCET_ENABLE=false
#   FAUCET_KEY=0x...                    # ONLY for throwaway devnets
#   FAUCET_DRIP_AMOUNT=1000000000000000000
#
# Metrics
#   METRICS_ENABLE=true
#   METRICS_HOST=0.0.0.0
#   METRICS_PORT=9110
#
# Ops
#   STARTUP_WAIT_SECS=90
#   RUN_MIGRATIONS=true
#   START_WORKER=true                   # start background verify queue scheduler
#   UVICORN_WORKERS=1
#   STUDIO_SVC_APP=studio_services.main:app
# ------------------------------------------------------------------------------

set -eu

# ---- defaults ---------------------------------------------------------------
: "${RPC_URL:=http://127.0.0.1:8545}"
: "${WS_URL:=ws://127.0.0.1:8545/ws}"
: "${CHAIN_ID:=1}"

: "${SERVICES_HOST:=0.0.0.0}"
: "${SERVICES_PORT:=8081}"
: "${SERVICES_CORS:=*}"
: "${SERVICES_CORS_ALLOWLIST:=${SERVICES_CORS}}"
: "${SERVICES_RATE_LIMITS:=default}"
: "${SERVICES_LOG_LEVEL:=info}"
: "${SERVICES_LOG_FORMAT:=json}"

: "${SERVICES_DB_BACKEND:=sqlite}"
: "${SERVICES_SQLITE_FILE:=studio_services.db}"
: "${SERVICES_ROCKS_DIR:=studio_services_rocks}"
: "${SERVICES_STORAGE_DIR:=/data/services}"
: "${SERVICES_ARTIFACTS_DIR:=${SERVICES_STORAGE_DIR}/artifacts}"

: "${SERVICES_API_KEYS:=}"

: "${FAUCET_ENABLE:=false}"
: "${FAUCET_KEY:=}"
: "${FAUCET_DRIP_AMOUNT:=1000000000000000000}"

: "${METRICS_ENABLE:=true}"
: "${METRICS_HOST:=0.0.0.0}"
: "${METRICS_PORT:=9110}"

: "${STARTUP_WAIT_SECS:=90}"
: "${RUN_MIGRATIONS:=true}"
: "${START_WORKER:=true}"
: "${UVICORN_WORKERS:=1}"
: "${STUDIO_SVC_APP:=studio_services.main:app}"

CONFIG_PATH="/etc/animica/services.toml"
mkdir -p "$(dirname "${CONFIG_PATH}")" "${SERVICES_STORAGE_DIR}" "${SERVICES_ARTIFACTS_DIR}"

# ---- helpers ----------------------------------------------------------------
comma_to_toml_array() {
  v="$1"
  if [ -z "${v}" ]; then printf '[]'; return; fi
  v=$(printf "%s" "${v}" | sed 's/ *, */,/g')
  IFS=','; set -- ${v}; unset IFS
  printf '['
  first=1
  for item in "$@"; do
    s="${item}"
    [ "${first}" -eq 0 ] && printf ', '
    printf '"%s"' "${s}"
    first=0
  done
  printf ']'
}

bool_to_toml() {
  case "${1:-}" in
    1|true|TRUE|True|yes|YES|on|ON)  printf 'true' ;;
    *)                               printf 'false' ;;
  esac
}

wait_for_http() {
  url="$1"; timeout="${2:-60}"
  echo ">> Waiting for ${url} (timeout ${timeout}s)…"
  i=0
  while [ "${i}" -lt "${timeout}" ]; do
    if command -v wget >/dev/null 2>&1; then
      if wget -q -O /dev/null "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"; return 0
      fi
    elif command -v curl >/dev/null 2>&1; then
      if curl -fsS "${url}" >/dev/null 2>&1; then
        echo ">> OK: ${url}"; return 0
      fi
    fi
    i=$((i+1))
    sleep 1
  done
  echo "ERROR: timed out waiting for ${url}" >&2
  return 1
}

# ---- derive DB URI -----------------------------------------------------------
case "${SERVICES_DB_BACKEND}" in
  sqlite)
    DB_FILE="/data/${SERVICES_SQLITE_FILE}"
    DB_URI="sqlite:///${DB_FILE}"
    ;;
  rocksdb|rocks)
    DB_DIR="/data/${SERVICES_ROCKS_DIR}"
    mkdir -p "${DB_DIR}"
    DB_URI="rocksdb://${DB_DIR}"
    ;;
  *)
    echo "ERROR: Unsupported SERVICES_DB_BACKEND='${SERVICES_DB_BACKEND}'" >&2
    exit 2
    ;;
esac

# ---- render config -----------------------------------------------------------
echo ">> Rendering ${CONFIG_PATH}"
{
  echo '# Autogenerated by entrypoints/services.sh'
  echo ''
  echo '[server]'
  printf 'host = "%s"\n' "${SERVICES_HOST}"
  printf 'port = %s\n' "${SERVICES_PORT}"
  printf 'cors_allowlist = ' ; comma_to_toml_array "${SERVICES_CORS_ALLOWLIST}"; echo
  printf 'rate_limits = "%s"\n' "${SERVICES_RATE_LIMITS}"
  echo ''
  echo '[logging]'
  printf 'level = "%s"\n' "${SERVICES_LOG_LEVEL}"
  printf 'format = "%s"\n' "${SERVICES_LOG_FORMAT}"
  echo ''
  echo '[rpc]'
  printf 'url = "%s"\n' "${RPC_URL}"
  printf 'ws_url = "%s"\n' "${WS_URL}"
  printf 'chain_id = %s\n' "${CHAIN_ID}"
  echo ''
  echo '[storage]'
  printf 'db_uri = "%s"\n' "${DB_URI}"
  printf 'artifacts_dir = "%s"\n' "${SERVICES_ARTIFACTS_DIR}"
  printf 'root_dir = "%s"\n' "${SERVICES_STORAGE_DIR}"
  echo ''
  echo '[security]'
  printf 'api_keys = ' ; comma_to_toml_array "${SERVICES_API_KEYS}"; echo
  echo ''
  echo '[faucet]'
  printf 'enable = %s\n' "$(bool_to_toml "${FAUCET_ENABLE}")"
  # Note: FAUCET_KEY is sensitive; passed via env, not persisted in TOML unless explicitly set
  if [ -n "${FAUCET_KEY}" ]; then
    printf 'key = "%s"\n' "${FAUCET_KEY}"
  fi
  printf 'drip_amount = "%s"\n' "${FAUCET_DRIP_AMOUNT}"
  echo ''
  echo '[metrics]'
  printf 'enable = %s\n' "$(bool_to_toml "${METRICS_ENABLE}")"
  printf 'host = "%s"\n' "${METRICS_HOST}"
  printf 'port = %s\n' "${METRICS_PORT}"
} > "${CONFIG_PATH}"

export ANIMICA_SERVICES_CONFIG="${CONFIG_PATH}"
echo ">> ANIMICA_SERVICES_CONFIG=${ANIMICA_SERVICES_CONFIG}"

# ---- migrations (best-effort) -----------------------------------------------
if [ "$(bool_to_toml "${RUN_MIGRATIONS}")" = "true" ]; then
  echo ">> Running DB migrations…"
  if command -v python >/dev/null 2>&1; then
    # Prefer the CLI if available
    if python -c "import studio_services.cli" >/dev/null 2>&1; then
      python -m studio_services.cli migrate || {
        echo "WARN: CLI migrate failed; trying shell script if present…" >&2
        if [ -x /app/studio-services/scripts/migrate.sh ]; then
          /app/studio-services/scripts/migrate.sh || true
        fi
      }
    elif [ -x /app/studio-services/scripts/migrate.sh ]; then
      /app/studio-services/scripts/migrate.sh || true
    else
      echo "WARN: migration tool not found; continuing without explicit migration." >&2
    fi
  fi
fi

# ---- readiness ---------------------------------------------------------------
if ! wait_for_http "${RPC_URL%/}/readyz" "${STARTUP_WAIT_SECS}"; then
  echo ">> Falling back to ${RPC_URL%/}/healthz"
  wait_for_http "${RPC_URL%/}/healthz" "${STARTUP_WAIT_SECS}" || true
fi

# ---- start optional background worker ---------------------------------------
if [ "$(bool_to_toml "${START_WORKER}")" = "true" ]; then
  echo ">> Starting verify queue scheduler (background)…"
  if python -c "import studio_services.tasks.scheduler" >/dev/null 2>&1; then
    # Run detached so the web server can stay PID 1
    python -m studio_services.tasks.scheduler &
  else
    echo "WARN: scheduler module not found; skipping background worker." >&2
  fi
fi

# ---- start web server --------------------------------------------------------
echo ">> Starting Studio Services (${STUDIO_SVC_APP}) on ${SERVICES_HOST}:${SERVICES_PORT}"
if command -v uvicorn >/dev/null 2>&1; then
  exec uvicorn "${STUDIO_SVC_APP}" --host "${SERVICES_HOST}" --port "${SERVICES_PORT}" --workers "${UVICORN_WORKERS}"
else
  case "${STUDIO_SVC_APP}" in
    *:app)
      mod="${STUDIO_SVC_APP%:*}"
      echo ">> uvicorn not found; trying 'python -m ${mod}'"
      exec python -m "${mod}"
      ;;
    *)
      echo "ERROR: uvicorn not installed and STUDIO_SVC_APP is not module:app" >&2
      exit 3
      ;;
  esac
fi
